### ISSUE TITLE
Know Sure Thing (KST) is different to that of stockcharts.com/school

### ISSUE THREAD

**Issue by saroun74** [bukosabino/ta#1]
Thank you for this package.

I found that kst implementation is different to 
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:know_sure_thing_kst

As for me, I'm adding another function which makes difference between kst and sig.
def kst_sig(close, r1=10, r2=15, r3=20, r4=30, n1=10, n2=10, n3=10, n4=15, nsig=9, fillna=False):
    ....
    return pd.Series(kst-sig, name='kst-sig')

**Comment by bukosabino** [comment]
Hi @saroun74 ,

The implementation of ROC (Rate Of Change) is different than your link, but it's right. The result is the same if you use:

`close / close.shift(r1) - 1`
or 
`(close - close.shift(r1)) / close.shift(r1)`

So, I think we can change the implementation from:

```python
    rocma1 = (close / close.shift(r1) - 1).rolling(n1).mean()
    rocma2 = (close / close.shift(r2) - 1).rolling(n2).mean()
    rocma3 = (close / close.shift(r3) - 1).rolling(n3).mean()
    rocma4 = (close / close.shift(r4) - 1).rolling(n4).mean()
```

to:

```python
    rocma1 = ((close - close.shift(r1)) / close.shift(r1)).rolling(n1).mean()
    rocma2 = ((close - close.shift(r2)) / close.shift(r2)).rolling(n2).mean()
    rocma3 = ((close - close.shift(r3)) / close.shift(r3)).rolling(n3).mean()
    rocma4 = ((close - close.shift(r4)) / close.shift(r4)).rolling(n4).mean()
```

Perhaps the code is more clear in this way.

What do you think?

**Comment by saroun74** [comment]
I'm not mentioning the implementation of ROC.
This package returns the 'sig', but the sockcharts.com link guides 'kst - sig' as indicator.

**Comment by bukosabino** [comment]
Ok, I understand your suggestion now.

So, I think we could get 3 indicators: KST, KST Signal, and KST - KST Signal.

![test](https://user-images.githubusercontent.com/4375209/39662327-204e7518-5060-11e8-92b4-929977ef2966.png)

What do you think?

**Comment by bukosabino** [comment]
Library updated to new version 0.1.5.

Now,  we get 3 indicators from KST: KST, KST Signal, and KST - KST Signal.
