### ISSUE TITLE
Latest examples for bb return 0

### ISSUE THREAD

**Issue by dreamerx88** [bukosabino/ta#101]
Hello, in testing the posted example in https://github.com/bukosabino/ta and using the csv data you provided (I kept only the last say 60 lines), printing df shows zeros for the bb_high_indicator and bb_low_indicator columns that result. Examples using other indicators (macd, macd_signal, ema) with the def approach are generating results...so it looks like it's just bb that is not working?

**Comment by bukosabino** [comment]
Hi @dreamerx88 ,

Bollinger Bands Indicators are working fine. Recently I have added some tests: https://github.com/bukosabino/ta/blob/feature/tests/ta/tests/volatility.py#L30 with this dataset: https://github.com/bukosabino/ta/blob/feature/tests/ta/tests/data/cs-bbands.csv

Probably the dataset you are using doesn't have any example where close price cross up the higher Bollinger Band or close price cross down the lower Bollinger Band.

So, please try with other datasets if you want to see 1s.

Let me know if you have any problems.

Best,
Dario.
