### ISSUE TITLE
VI Negative giving Value Error

### ISSUE THREAD

**Issue by topchatz** [bukosabino/ta#102]
Hi guys,

I'm trying to use the Vortex Indicators and am getting this error message:

`ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

The line of code I have used is:

`data['VI_neg'] = ta.vortex_indicator_neg(prices['h'], prices['l'], prices['c'], n=72, fillna=True)`

I am also getting the following error message when trying to use the money flow index:

`pandas.core.indexes.base.InvalidIndexError: Reindexing only valid with uniquely valued Index objects`

Again my code for that is:

`data['MFI'] = ta.money_flow_index(prices['h'], prices['l'], prices['c'], prices['v'], n=72, fillna=True)`

It just appears to be these I'm having trouble with, the others all seem to load fine. I'm testing them with Bitcoin hourly data from Binance as well by the way. Any suggestions would be great, many thanks

**Comment by bukosabino** [comment]
Hi @topchatz 

I think this is related to the dataset. Are you working with missing values (NaN data)? Could you share the dataset with me to try a test?

I have worked in a class-based API for the library. It is more efficient. Please take a look:

```python
    # Vortex Indicator
    indicator = VortexIndicator(high=prices['h'], low=prices['l'], close=prices['c'], n=72, fillna=True)
    data['VI_neg'] = indicator.vortex_indicator_pos()
    data['VI_pos'] = indicator.vortex_indicator_neg()
    data['VI_diff'] = indicator.vortex_indicator_diff()

    # Money Flow Indicator
    df[f'{colprefix}momentum_mfi'] = MFIIndicator(
        high=prices['h'], low=prices['l'], close=prices['c'], volume=prices['v'], n=72, fillna=True).money_flow_index()
```

Best,
Dario

**Comment by topchatz** [comment]
Hi mate, thanks for the reply.

I just upgraded to the latest version and tried your code above but `VortexIndicator` is causing a NameError:

`NameError: name 'VortexIndicator' is not defined`

My data set is quite large but it's basically just a load of price data, so not sure how best to share with you. But I have checked for NaNs before and there aren't any.

Many thanks

**Comment by bukosabino** [comment]
Hi @topchatz 

You need to import the indicator in this way:

```python
from ta.trend import VortexIndicator
```

Could you try uploading the dataset in Google Drive and share with me the link?

Best,
Dario
