### ISSUE TITLE
ATR giving Error

### ISSUE THREAD

**Issue by eveJiang** [bukosabino/ta#103]
Hi~
Thanks for your work. I plan to use your project to generate some indicators. But I got this error message QAQ:
**ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().**

I have also attached my dataset here. Would you please give me some suggestions? Many thanks.
[test.xlsx](https://github.com/bukosabino/ta/files/3882482/test.xlsx)

**Comment by bukosabino** [comment]
Hi @eveJiang ,

Please, share the code to get this error.

Best,
Dario

**Comment by jafetgado** [comment]
I experienced the same error. 

For some reason, ta.volatility.average_true_range prints out this error when the index of your dataframe is a datetime object.

To avoid this, transform the indices to integers.

```python
newindex = np.arange(df.shape[0])
high, low, close = df['high'], df['low'], df['close']
high.index, low.index, close.index = newindex, newindex, newindex
atr = ta.volatility.average_true_range(high, low, close, n=14)
```

**Comment by bukosabino** [comment]
Hi @eveJiang and @jafetgado ,

I have fixed the issue. You need to update the library, using the last version (0.5.23).

```
pip install -U ta
```

or 

```
pip install ta==0.5.23
```

Please, let me know if you get some other errors.

Best,
Dario
