### ISSUE TITLE
PSARIndicator

### ISSUE THREAD

**Issue by Yanboo73** [bukosabino/ta#108]
Don't see the class implemented

![Screen Shot 2019-12-02 at 2 16 07 PM](https://user-images.githubusercontent.com/3879109/69987795-4e8fe500-150e-11ea-8c3d-1c1a847b6c3c.png)

![Screen Shot 2019-12-02 at 2 13 49 PM](https://user-images.githubusercontent.com/3879109/69987663-fc4ec400-150d-11ea-8ad3-18b3087b8587.png)

**Comment by bukosabino** [comment]
Hi @Yanboo73 ,

PSAR has been included on v0.5.9. Please, update the version of the library

```sh
pip install -U ta
```

```sh
pip install ta==0.5.9
```

**Comment by Yanboo73** [comment]
Thank you!
