### ISSUE TITLE
check_fillna should use ffill not backfill

### ISSUE THREAD

**Issue by RichardDale** [bukosabino/ta#109]
As I understand the code, check_fillna.  Each indicator provides its own fill method. 

However, if the indicator doesn't have a default value, the pandas fill method with backfill is used.

This is not a good idea as it introduces an information leak - i.e. it's using the value derived from future bars.  'ffill' seems to be more appropriate here.

It's a fairly trivial fix to utils.py inside class IndicatorMixin/check_fillna around line 15.

**Comment by bukosabino** [comment]
Hi @RichardDale ,

Of course you are right, we need to fill data first in `ffill` mode and then we can apply the method selected by the programmer to fill the values for the first values (only if the user of the library wants to fill them).

The last commit in 'develop' branch add this idea. The next version of the library will add this feature.

Please, take a look to the updated code, and let me know what do you think: https://github.com/bukosabino/ta/blob/develop/ta/utils.py

Best,
Dario

**Comment by bukosabino** [comment]
Hi @RichardDale ,

This feature has been included in the last version of the library (v0.5.11).

To install the last ta version you can do:

```sh
pip install -U ta
```

**Comment by RichardDale** [comment]
Looks great - nice work Dario.
