### ISSUE TITLE
Adding a method for Bollinger Band Width 

### ISSUE THREAD

**Issue by rsandx** [bukosabino/ta#113]
This is a feature request for a simple function to return Bollinger Band Width directly:
def bollinger_wband(close, n=20, ndev=2, fillna=False):
    indicator = BollingerBands(close=close, n=n, ndev=ndev, fillna=fillna)
    return indicator.bollinger_wband()

**Comment by rsandx** [comment]
Thanks for considering the request. I know it's easy to calculate Simple Moving Average, which can be done by using volatility.bollinger_mavg currently, but it's probably not optimal as an independent function, can you consider to add a dedicate method for it, i.e. sma_indicator?

**Comment by bukosabino** [comment]
These features are included in the last library version (0.5.17).

Update to use it:

```bash
pip install -U ta
```
