### ISSUE TITLE
Ultimate Oscillator class is instantiated with hard coded values 

### ISSUE THREAD

**Issue by fettunch** [bukosabino/ta#114]
Hi @bukosabino ,

this library is very good. I am thinking to use it for one of my projects. 

In momentum.py class row 611 the UltimateOscillator is instantiated with hard coded values the row:

    return UltimateOscillator(
        high=high, low=low, close=close, s=7, m=14, len=28, ws=4.0, wm=2.0, wl=1.0, fillna=fillna).uo()

should be instead:

    return UltimateOscillator(
        high=high, low=low, close=close, s=s, m=m, len=len, ws=ws, wm=wm, wl=wl, fillna=fillna).uo()

I can make this change if you want. Let me know.

**Comment by fettunch** [comment]
I found other places whit hard-coded values a part from the ones I opened an issue: KeltnerChannel, Awesome Oscillator. 

I change the code and I have a branch ready. if you allow me to push it I can create a pull request for this topic.

**Comment by fettunch** [comment]
Hi @bukosabino, do you have any news on this thread?

**Comment by bukosabino** [comment]
Thank you @fettunch ,

I will fix asap

**Comment by bukosabino** [comment]
Hi @fettunch ,

All hardcoded values are fixed if you use the last version 0.5.13. To install the last version:

```
pip install -U ta
```

Please, let me know if you have more feedback for me. Thanks!

Best,
Dario
