### ISSUE TITLE
Rate of change hard-coded value

### ISSUE THREAD

**Issue by fettunch** [bukosabino/ta#115]
Hi @bukosabino ,

same issue I reported [here ](https://github.com/bukosabino/ta/issues/114)happens for the Rate of Change.  I will review other class instantiation to make sure the same bug is not spread some where else.

**Comment by fettunch** [comment]
Hi @bukosabino, do you have any news on this thread?

**Comment by bukosabino** [comment]
Duplicated https://github.com/bukosabino/ta/issues/114
