### ISSUE TITLE
Head and shoulder pattern

### ISSUE THREAD

**Issue by martinbouhier** [bukosabino/ta#124]
Do you have any way to detect head and shoulder pattern?

**Comment by bukosabino** [comment]
Hi @martinbouhier ,

Not at this moment. But, I think this is an excellent feature to add in the future.

I will work in this way, and I will come back to you when I get advances.

Best,
Dario

**Comment by bukosabino** [comment]
https://towardsdatascience.com/detection-of-price-support-and-resistance-levels-in-python-baedc44c34c9
