### ISSUE TITLE
keltner_channel_hband incorrect output?

### ISSUE THREAD

**Issue by khoing1111** [bukosabino/ta#126]
I take a look at the following code

https://github.com/bukosabino/ta/blob/0.5.11/ta/volatility.py

line 210

It look weird that keltner_channel_hband use self._tp instead of self._tp_high?

```
    def keltner_channel_hband(self) -> pd.Series:
        """Keltner Channel High Band
        Returns:
            pandas.Series: New feature generated.
        """
        tp = self._check_fillna(self._tp, value=-1)
        return pd.Series(tp, name='kc_hband')
```

**Comment by bukosabino** [comment]
Hi @khoing1111 ,

You are right. I will fix it asap.

Best,
Dario

**Comment by bukosabino** [comment]
https://github.com/bukosabino/ta/commit/5438c949518274d0f6957480ac0f97f735c0cd98

fixing bug: keltner channel high band calculation. Also, included percentage band and width band indicators for keltner channel. Also, included 2 ways to calculate the centerline of Keltner Channel: original version (sma of typical price) vs modern version (ema of close)

**Comment by bukosabino** [comment]
The last library version (0.5.15) includes this feature.

```bash
pip install -U ta
```

Thanks @khoing1111
