### ISSUE TITLE
VWAP Indicator Implementation

### ISSUE THREAD

**Issue by bukosabino** [bukosabino/ta#130]
From: https://medium.com/@neonguru/it-would-be-nice-if-it-included-vwap-22fa4e80584f

It would be nice if it included VWAP.

More info: https://school.stockcharts.com/doku.php?id=technical_indicators:vwap_intraday

**Comment by Glyphack** [comment]
Hi, I can work on this issue.

**Comment by bukosabino** [comment]
Great @Glyphack !

I am here to help you too.

Best,
Dario

**Comment by ZachNagengast** [comment]
Any update on this? I may look into it unless its already in progress.

**Comment by Glyphack** [comment]
Actually I've been pretty busy and because of that I did not post any updates. I'll post updates today.

**Comment by bukosabino** [comment]
The indicator was implemented by @Glyphack here: https://github.com/bukosabino/ta/pull/140 and it has been added in the last version (0.5.18).

To update the library:

```bash
pip install -U ta
```

Thank you for your collaboration.

Best,
Dario
