### ISSUE TITLE
bollinger_lband_indicator calls BollingerBands.bollinger_hband_indicator

### ISSUE THREAD

**Issue by fettunch** [bukosabino/ta#132]
Hi @bukosabino,

bollinger_lband_indicator return the wrong results by calling BollingerBands.bollinger_hband_indicator.

If you allow me I can create a pull request to fix this glitch.

**Comment by bukosabino** [comment]
Hi @fettunch ,

Of course, you are welcome to do it!

**Comment by bukosabino** [comment]
Hi @fettunch,

Solved here https://github.com/bukosabino/ta/pull/134

**Comment by bukosabino** [comment]
This fix is included in the last library version (0.5.17).

Update to use it:

```bash
pip install -U ta
```
