### ISSUE TITLE
API Requirements/Expectations

### ISSUE THREAD

**Issue by twopirllc** [bukosabino/ta#14]
Just curious on what sort of requirements or expectations you have regarding the API now and moving forward.

- Limited to return a single Series? Is returning a DataFrame an option for indicators that return multiple series, such as MACD, BBANDs, et al?
- Are the indicators to be decoupled and not rely on others for computation?  For instance, MACD relying on SMAs?

Thanks
KJ

**Comment by bukosabino** [comment]
Hi @twopirllc ,

* Absolutely, it is an option.
* At this moment MACD and SMA are decoupled.

I am completely open to change the code implementation. Do you think these ideas are a better option for the library?

**Comment by twopirllc** [comment]
Hi Darío,

Sorry been a bit busier this week.  Between that, I have been busy reevaluating and modernizing some of my old indicators and analyzing indicators that others have written or ported from other code.

- Cool. I agree in most cases, a single series is all that is needed.  While some others, it might been be more efficient to have one method return a DataFrame instead.  At least to avoid code duplication, like MACD, ADX, et al.
- I suppose for simpler indicators like MACD decoupled is fine since SMA can be easily calculated within it utilizing Pandas builtin methods.

I am not entirely sure at this point if the ideas I presented are better without building out a working subset and seeing how easily they can be adapted to work with Dask.

Thanks,
KJ

**Comment by twopirllc** [comment]
Hi Darío,

What about extending the DataFrame?  ([https://pandas.pydata.org/pandas-docs/stable/extending.html](url)) This is promising and 'ta' has not been taken yet.

I have part of a working model in development.  For example for the CCI Indicator,
it can be called one of two ways: df.ta.cci(length=20) or df.ta(kind='cci', length=20)
and it will return whatever it's result is.  I have also added a kwarg called 'append' to
automatically add the resultant columns from an indicator to the original DataFrame df.

I will create a new branch and add it to the module with some indicators and see what you think over this coming week.

Thanks,
KJ

**Comment by bukosabino** [comment]
Ok @twopirllc , 

I'm not sure if I understand completely your idea. You would need to call cci with "high", "low" and "close" params too... 

Yes, you can work in a new branch ;)

**Comment by twopirllc** [comment]
Yes, those parameters are included already from the existing DataFrame or they can be passed in directly.

Thanks

**Comment by twopirllc** [comment]
Hey Darío,

Wish I had more time to get more done, however this is what I have so far.  Check out the README for the details.  In short, I have refactored it, made it a Pandas Extension, and added 30 more common indicators.

Give it a run and check it out.
KJ

**Comment by bukosabino** [comment]
Hi KJ,

I am checking the code and I think your work is absolutely awesome!

What do you want to do with your fork/library?

**Comment by twopirllc** [comment]
Hi Darío,

Thanks!  I still have some more work to do on it.  Such as additional refactoring and cleaning.  I also plan to include some differential analysis between a couple of other known working TA libraries to ensure tolerable accuracy.  Of course there are always additional indicators to incorporate.

What are your thoughts and suggestions?

Thanks,
KJ
