### ISSUE TITLE
Ichimoku tenkansen and kijunsen 

### ISSUE THREAD

**Issue by HamidMousavi** [bukosabino/ta#155]
hi, I need to get Ichimoku tenkansen and kijunsen and chikou_span values, is it possible with ta? if not, please add this feature.
Thanks.

**Comment by bukosabino** [comment]
Hi @HamidMousavi ,

At this moment you can get the Senkou `span a` and `span b` using:

```
from ta.trend import IchimokuIndicator


indicator = IchimokuIndicator(high=df[high], low=df[low], n1=9, n2=26, n3=52, visual=False, fillna=fillna)
df[f'{colprefix}trend_ichimoku_a'] = indicator.ichimoku_a()
df[f'{colprefix}trend_ichimoku_b'] = indicator.ichimoku_b()
```

I will add methods for Tenkan-sen, Kijun-sen, as soon as possible.

Check the documentation to understand the input parameters. Please, note the implementation is based on https://school.stockcharts.com/doku.php?id=technical_indicators:ichimoku_cloud

Best,
Dario

**Comment by bukosabino** [comment]
Hi @HamidMousavi ,

I have updated the library to get Tenkan-sen and Kijun-sen time series. You need to update the last library version (0.5.24).

```
pip install -U ta
```

or 

```
pip install ta==0.5.24
```

The way to call them:

```
from ta.trend import IchimokuIndicator


indicator = IchimokuIndicator(high=df[high], low=df[low], n1=9, n2=26, n3=52, visual=False, fillna=fillna)
df[f'trend_ichimoku_conv'] = indicator.ichimoku_conversion_line()
df[f'trend_ichimoku_base'] = indicator.ichimoku_base_line()
df[f'trend_ichimoku_a'] = indicator.ichimoku_a()
df[f'trend_ichimoku_b'] = indicator.ichimoku_b()
```

Let me know if you have any problems. I still need to write some tests with input and expected results for this indicator. I will write ASAP.

Best,
Dario

**Comment by gambitov** [comment]
Dear @bukosabino , I have a question about:
 `'trend_ichimoku_a', 'trend_ichimoku_b', 'trend_visual_ichimoku_a', 'trend_visual_ichimoku_b'`
I have notices that trend_visual_ichimoku_a and trend_visual_ichimoku_b are in fact SenkouA and SenkouB but I do not understand what is trend_ichimoku_a and trend_ichimoku_b, may you clarify this? please.
