### ISSUE TITLE
Strange values EMA (?)

### ISSUE THREAD

**Issue by PhantoNull** [bukosabino/ta#159]
Hello, I was in the testing phase and I cannot understand why I got this strange values.

Basically what I needed was a **percentage volume oscillator** on 30-60 period.

So I started coding it and that's something curious since I can't find a way to get Tradingview values on my script.

Values from tradingView-Binance BTC/Usdt are just okay (volume also)
I have highlighted just few things of the last hystorical candle on the graph to compare on the next image.
Except RSI (almost same value) I got some really strange values for this PVO
![image](https://user-images.githubusercontent.com/65261018/81756040-e250de80-94ba-11ea-8594-03daab3bf844.png)

I requested the last 66 hystorical (just to be sure and print some more result to check besides the last one) 15 min candles back and printed out the last 3.
It doesn't fetch the last candle (still open) on the graph obviously.
![image](https://user-images.githubusercontent.com/65261018/81756120-204e0280-94bb-11ea-821a-8bdca1bad1aa.png)

And this is the code for the pvo:
![image](https://user-images.githubusercontent.com/65261018/81756430-06f98600-94bc-11ea-9d5e-8b568f0cf20f.png)

What could be the problem?
Thanks!

**Comment by Phanto90** [comment]
I just tried to add some more hystorical data and it just fixed. Felt a little dumb.

**Comment by bukosabino** [comment]
Hi @Phanto90 ,

Last version 0.5.25 (updated yesterday) fixes some problems related to the first values, probably it was solved. Let me know if you try again using the last version.

Also, I encourage you to add this **Percentage Volumen Oscillator** to the library.

Best,
Dario

**Comment by bukosabino** [comment]
Closing, because at this moment, PVO is available in the library.
