### ISSUE TITLE
File datas.csv does not exist: 'datas.csv'

### ISSUE THREAD

**Issue by Adolf-L** [bukosabino/ta#161]
![image](https://user-images.githubusercontent.com/10137107/82142936-a29b4580-9872-11ea-99fc-f4c0ac4158b9.png)

where is the problem?

**Comment by bukosabino** [comment]
Hi @Adolf-L ,

`datas.csv` is just a CSV example. You should use your dataset. If you want to use this example dataset, you can download the file here: https://github.com/bukosabino/ta/blob/master/ta/tests/data/datas.csv

**Comment by bukosabino** [comment]
I close the issue.

Please, let me know if you have any more doubt/questions.

Best,
Dario

**Comment by Adolf-L** [comment]
thx, I have done
