### ISSUE TITLE
Changing ema period

### ISSUE THREAD

**Issue by gambitov** [bukosabino/ta#172]
I want to override ema for an specific period slow(55) and fast (10) ema, could you help me? please.
And I like to know how can chage period for MACD.

Thank you for your help

**Comment by bukosabino** [comment]
Hi @gambitov ,

You can try somethin like this:

```python
import pandas as pd

from ta.trend import EMAIndicator
from ta.utils import dropna


# Load datas
df = pd.read_csv('ta/tests/data/datas.csv', sep=',')

# Clean NaN values
df = dropna(df)

# Calculate EMAs
df['trend_ema_fast'] = EMAIndicator(close=df[close], n=12).ema_indicator()
df['trend_ema_slow'] = EMAIndicator(close=df[close], n=55).ema_indicator()
```

Let me know if it is clear for you.

Best,
Dario

**Comment by gambitov** [comment]
dear @bukosabino, I had to change [close] for ['Close'] and it works perfectly. Thank you so much.
