### ISSUE TITLE
as_format issue 

### ISSUE THREAD

**Issue by ashraf-01** [bukosabino/ta#176]
Hi all

I got the below attached error while executing 
data.ta.mp = True
data.ta.strategy()
sorry here is the screenshot attached 
your input is highly appreciated 

[screenshot.docx](https://github.com/bukosabino/ta/files/4925857/screenshot.docx)

**Comment by bukosabino** [comment]
Hi @ashraf-01 ,

Sorry pandas-ta is another Python library to do technical analysis. Please contact to @twopirllc 

Best,
Dario
