### ISSUE TITLE
Example/Tests not working correctly

### ISSUE THREAD

**Issue by TheCrockett** [bukosabino/ta#193]
# python -m unittest discover
coverage run tests.py
/tmp/ta/ta/trend.py:608: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i]/self._trs[i])
/tmp/ta/ta/trend.py:612: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i]/self._trs[i])
.............................................................................................................
----------------------------------------------------------------------

I suspect this is is because manually running the all_features_example.py gives the same issue, which i've also included in the dockerfile.

**Comment by TheCrockett** [comment]
Here is a Dockerfile that you can reporoduce: 

FROM fedora:latest
ENV TZ=America/New_York
RUN yum install which initscripts -y
RUN yum install mysql bc jq git gcc freetype-devel gcc-c++ python3-devel make -y 
RUN yum install python3-pip -y
RUN pip3 install awscli 
RUN pip3 install --upgrade ta
run rpm -qa |grep pytho
RUN cd /tmp; git clone  -b '0.5.25' --single-branch --depth 1  https://github.com/bukosabino/ta.git
RUN cd /tmp/ta; pip3 install -r play-requirements.txt; make test
RUN cd /tmp/ta/examples_to_use; python3 all_features_example.py

**Comment by bukosabino** [comment]
Hi @TheCrockett ,

This is a warning, not an error. 

We are working to solve it.

Best,
Dario
