### ISSUE TITLE
Bug within UlcerIndex feature

### ISSUE THREAD

**Issue by vinopm** [bukosabino/ta#205]
Hi, 

There is an issue with the newly introduced UlcerIndex feature. 

Currently when calling the `add_volatility_ta(df...` function within wrapper.py, the DataFrame returned has a non numerical UlcerIndex column, where a reference to an UlcerIndex object exists within each row, instead of the correct float representation of the feature.

I have created a PR to ensure that the Ulcer Index feature values are returned in numerical representation within the DataFrame instead of as an UlcerIndex object. 

Visual representation of the current issue:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/6901786/99322286-8f8c2100-2867-11eb-986c-86a1f9239797.png">

Please review: https://github.com/bukosabino/ta/pull/204 for the fix.

Many thanks!

**Comment by bukosabino** [comment]
Thanks for your work @vinopm ,

The fix has been included in a new version of the library (v0.6.1). 

Best,
Dario
