### ISSUE TITLE
TypeError when defining MACD parameters

### ISSUE THREAD

**Issue by MikeCas** [bukosabino/ta#218]
Hi, I am getting this error when using the parameter names 'window_slow', 'window_fast', and 'window_sign'. It works ok if I stop after the "close" parameter, but then I can't play with the window sizes. Is it something I've done wrong?

--> 730             ind_MACD = ta.trend.MACD(close=df["close"], window_slow=26, window_fast=12, window_sign=9)

**_TypeError: \_\_init\_\_() got an unexpected keyword argument 'window_slow'_**

**Comment by sedna16** [comment]
I'm also hitting this kind of error with SMAIndicator

--------------

__init__() got an unexpected keyword argument 'n'

**Comment by bukosabino** [comment]
Hi all, 

The last release of the library update (standardize) the name of some input argument for the indicators. It looks like you are using an old version code and the current version of the documentation. So, please, update the version of the `ta` library:

```
pip install -U ta
```

The last version number is v0.7.0. Let me know if it is solving your issues.

Best,
Dario

**Comment by sedna16** [comment]
Thanks Dario,

upgraded to 0.7.0

then I changed the arguments from n=int(num to window=int(num)

it worked for me

**Comment by emiliano890** [comment]
I have the same problem with macd

indicator_macd = ta.trend.MACD(data['Close'], window_slow = 26, window_fast = 12, window_sign = 9)

TypeError: __init__() got an unexpected keyword argument 'window_slow'

**Comment by emiliano890** [comment]
Same problem with adx

indicator_adx_neg = ta.trend.adx_neg(data.High, data.Low, data.Close, window=14)

adx_neg() got an unexpected keyword argument 'window'

**Comment by bukosabino** [comment]
Hi @emiliano890,

What version of the library which are you using? You can check the versions of your packages using the command:

```
pip freeze
```

Try to use the last one (0.8.0):

```
pip install ta==0.8.0
```

Please, take a look at an example of how to call the [MACD](https://github.com/bukosabino/ta/blob/390ce43a86f2094d30075eee36d92be96583f065/ta/wrapper.py#L248) and [ADX](https://github.com/bukosabino/ta/blob/390ce43a86f2094d30075eee36d92be96583f065/ta/wrapper.py#L340)

Let me know if you continue getting problems.

**Comment by emiliano890** [comment]
Hello Dario,

I have ta==0.8.0
ta.trend.adx_pos(high, low, close, window=14, fillna=False)
only work without window.
The same with MACD only work without the parameters (windows_slow/fast/sign)

**Comment by bukosabino** [comment]
Hi @emiliano890 

I will take a look ASAP.

Thanks!

**Comment by bukosabino** [comment]
Hi all, 

I am running every example that you expose on this topic:

![example ta](https://user-images.githubusercontent.com/4375209/150694064-f9a033e4-d448-4237-a0f6-8e4d0a1dab35.png)

I have used the last version of ta (0.9.0), and I can run with python3.6 and python3.8.

The data used are from a publicly available financial dataset: https://www.kaggle.com/c/g-research-crypto-forecasting/data

I close the issue, but please feel free to re-open it.

Thanks.
