### ISSUE TITLE
PPO & PVO with duplicate column name

### ISSUE THREAD

**Issue by MartinW90** [bukosabino/ta#231]
Hey, 
first of all thank you for providing this project, it makes it much easier for me:) I found that in the wrapper file for "add_momentum_ta" there seems to be a copy paste error and the columns for PVO are named the same as  the ones for PPO.

**Comment by bukosabino** [comment]
Hi @MartinW90 ,

The last version of the library (0.9.0) implements these changes.

Thanks, @MartinW90 

Best,
Dario
