### ISSUE TITLE
error: name 'add_all_ta_features' is not defined

### ISSUE THREAD

**Issue by akitxu** [bukosabino/ta#292]
Thanks for sharing this good work. I'm trying to get to know him better. I have found this bug.

 `import pandas as pd
import ta
import yfinance as yf

# Add ta features filling NaN values
df = yf.download("AAPL", start= '2015-1-4', end = '2021-12-30')
df = ta.utils.dropna(df)

df = add_all_ta_features( df, open="Open", high="High", low="Low", close='Close', volume="Volume", fillna=True)
df`

`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_10246/3945308011.py in <module>
      7 df = ta.utils.dropna(df)
      8 
----> 9 df = add_all_ta_features( df, open="Open", high="High", low="Low", close='Close', volume="Volume", fillna=True)
     10 df

NameError: name 'add_all_ta_features' is not defined`

¿What can be the cause?  Thanks in advance.

**Comment by lit26** [comment]
You are not importing the function. 
```python
df = ta.add_all_ta_features(...)
```

**Comment by bukosabino** [comment]
Also, you can import at the first of your script:

```
from ta import add_all_ta_features
```
