### ISSUE TITLE
can we have function of generating simple moving average?

### ISSUE THREAD

**Issue by marcusau** [bukosabino/ta#3]
Hi sir,

   this is a very nice open-library. highly appreciated.
   One simple question, can we generate simple moving average with ta library in our python???

   Thanks

**Comment by bukosabino** [comment]
Hi marcusau,

It isn't implemented. But, you can use something like this:

```python
close.ewm(n).mean()
```

Where 'close' is the column you want to use and 'n' is the size of the window.

**Comment by ftuyama** [comment]
By design, I think it would be interesting to include this functionality, even though it's quite simple.
