### ISSUE TITLE
FutureWarning (with pandas 1.5.1)

### ISSUE THREAD

**Issue by i-gutierrez** [bukosabino/ta#308]
trend.py:730: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. (...)

Same thing on line 748 and 760. It's not really important at the moment but it's a quick fix (just add iloc after dropna),
and because I don't like ignoring warnings I already have the pull request ready :)

**Comment by lanigo-coder** [comment]
Same issue in volatility.py:50
