### ISSUE TITLE
icichimoku future values missing?

### ISSUE THREAD

**Issue by bizso09** [bukosabino/ta#31]
According to https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:ichimoku_cloud
for icichimoku cloud the values are shifted forward. Where can I get these values, are they discarded?

**Comment by bukosabino** [comment]
Hi @bizso09 , 

Thank you for the advice. But, I think the current implementation of the indicators is good.

Ichimoku indicator is plotted 26 periods in the future, you can read about this:

https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:ichimoku_cloud
http://www.kumotrader.com/ichimoku_wiki/index.php?title=Ichimoku_components#Senkou_Span_A
https://stackoverflow.com/questions/28477222/python-pandas-calculate-ichimoku-chart-components

**Comment by bizso09** [comment]
okay, thanks. I'm new to pandas. Could you explain how I can get the values. My understanding of pd.shift() is that it discards the values or replaces them with nan

```
In [2]: pd.Series([1,2,3,4,5])
Out[2]:
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]: pd.Series([1,2,3,4,5]).shift(2)
Out[3]:
0    NaN
1    NaN
2    1.0
3    2.0
4    3.0
dtype: float64
```
The most recent values 4, and 5 are now missing

**Comment by bukosabino** [comment]
You are right, pd.shift function works in this way. 

But, I think Ichimoku implementation need to use pd.shift() because we need to move time forwards 26 periods (normally) into the future.

**Comment by bizso09** [comment]
It seems to me that the period is shifted forward for display reasons. When the indicator is plotted in a trading terminal, it's visually more appealing to see the cloud towards the right. Still, the **trader uses these future values** to make decisions.

However, when we shift the values in pandas, **those values are discarded**. Therefore, we don't have access to those values any more. Hence we use stale information, which is incorrect

Therefore, there is clearly a bug in the current implementation.

I have two suggested solutions:

1. Do not shift the values, as it is purely for cosmetic purpose.
2. Shift the values, but ensure that the returned series indexes future dates, so that the values can be retrieved after shift.

**Comment by bukosabino** [comment]
Hi @bizso09 ,

Finally, I have decided to parameter this idea about the visualization of shifted values. So, the users can decide about this. By default, the function doesn't shift the data.

What do you think?

Thank you.

**Comment by twopirllc** [comment]
Hi @bizso09 and Darío,

My fork of 'ta' currently returns two DataFrames of Ichimoku, data up to the current date and the future Span values.  There is one caveat in creating the future Spans and that is the time frame of the data.  Currently it **only** calculates future Business Days and not any other time frames.  Unfortunately I have not had the time to incorporate other time frames yet, but I could use some help in that department in making it more robust.

Here is an example of my Ichimoku Results, mind the dates... that's some Bokeh code I have to fix.  
![bokeh_plot](https://user-images.githubusercontent.com/18198392/48038487-adc1d100-e125-11e8-8d6b-d32e5172245c.png)

What do you think?  Suggestions?

Thanks,
KJ
