### ISSUE TITLE
calculate daily return will use future infomation

### ISSUE THREAD

**Issue by leewi9** [bukosabino/ta#323]
```python
class DailyReturnIndicator(IndicatorMixin):
    """Daily Return (DR)

    Args:
        close(pandas.Series): dataset 'Close' column.
        fillna(bool): if True, fill nan values.
    """

    def __init__(self, close: pd.Series, fillna: bool = False):
        self._close = close
        self._fillna = fillna
        self._run()

    def _run(self):
        self._dr = (
            self._close / self._close.shift(1, fill_value=self._close.mean())
        ) - 1
        self._dr *= 100
```

so `fill_value` here use `self._close.mean()`, this will bring in future information, because mean is calculated by all close price in datasets

**Comment by yarimiz** [comment]
I created https://github.com/bukosabino/ta/pull/324 to fix this issue. But unfortunately I'm pretty sure this repository is not maintained anymore as no commits has been made for more than a year now.

It's better to not use this function at all for now, and just create this simple indicator yourself.

**Comment by bukosabino** [comment]
Hi @yarimiz and @leewi9,

Thanks for bringing this bug!

Working on merging the PR suggested by @yarimiz

**Comment by bukosabino** [comment]
Hi @yarimiz and @leewi9 ,

The last version of the library (0.10.3) implements these changes.

Thank you all!

Best,
Dario
