### ISSUE TITLE
Bug with ADI calculation

### ISSUE THREAD

**Issue by jfeust** [bukosabino/ta#40]
https://github.com/bukosabino/ta/blob/953be3d7bdd1b1ec2442701e508d565a1ebe8e90/ta/volume.py#L33-L34

I believe this not calculating the ADI correctly.

Per wikipedia the ADI should be `ADI(prev) + volume X CLV`
What those lines above are doing is `(volume x CLV)(prev) + (volume x CLV)`

So it's not propagating the previous ADI value to calculate the next ADI value, but rather the previous (volume x CLV) value.

**Comment by bukosabino** [comment]
Hi @jfeust,

Thank you so much, and sorry about the time delay to answer.

Finally, I have fixed the ADI indicator using `cumsum` Pandas function, and I have written some tests to validate the results (following the dataset on https://school.stockcharts.com/doku.php?id=technical_indicators:accumulation_distribution_line).

Please, take a look at this [commit](https://github.com/bukosabino/ta/pull/88/commits/3c63715901eeed5d79bfb29345a501b5a47c24eb), and let me know your opinion.

Best,
Dario

**Comment by bukosabino** [comment]
The new implementation was included in the last version (0.5.6). Instructions to update:

```sh
pip install --upgrade ta
```

or 

```sh
pip install ta==0.5.6
```

Best,
Dario
