### ISSUE TITLE
I can not install ta with pip help plss

### ISSUE THREAD

**Issue by guney1** [bukosabino/ta#56]
Hey this is the error I get, would be really happy if someone can help me, thankss

Collecting ta
  Using cached https://files.pythonhosted.org/packages/ba/09/149cb10cbd6b98cbcbaa6f74169b4f1f2ce6df144335bea0df0eaa9e1b01/ta-0.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hc/b2dnskds513b2dxjnv8m3g_40000gn/T/pip-install-ceehcvvi/ta/setup.py", line 14, in <module>
        install_requires=open('requirements.txt').readlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by bukosabino** [comment]
Fixed on 0.4.3 version.

Try again, please.
