### ISSUE TITLE
Data from future

### ISSUE THREAD

**Issue by gkourogiorgas** [bukosabino/ta#57]
Hi

I wanted to ask if the add_all_ta_features uses data from future candles or just current and past only
Thanks
P.S. Great work

**Comment by bukosabino** [comment]
Hi,

This library uses data from a Pandas DataFrame with Open/High/Low/Close/Volume columns to get Technical Analysis features.

Best,
Dario

**Comment by gkourogiorgas** [comment]
Hi Dario. Thanks for your response. I am just asking if any of the indicators calculated use forward values or just current and lagged

**Comment by bukosabino** [comment]
current and past
