### ISSUE TITLE
Ease of Movement (EMV) (ta.volume)

### ISSUE THREAD

**Issue by zachjgal** [bukosabino/ta#58]
A few minor things:

1. The Ease function takes closing price as a positional argument, but the closing price isn't actually needed in the calculation.

2: The calculation itself is mostly correct, but is missing one step: It needs to be multiplied by 10^8 or 100,000,000.

3: The default n is 20, but I've only ever seen EMV calculated with n=14

**Comment by bukosabino** [comment]
Hi @zachjgal 

Each point is fixed at this moment.

Thank you so much, and sorry about the time delay to answer.

Best,
Dario
