### ISSUE TITLE
Error in ATR calculation

### ISSUE THREAD

**Issue by coltonfsmith** [bukosabino/ta#59]
Thank you for all the work that you've put into this library. It is very useful! I was just using the ATR function and believe I found a minor error in the calculation. After calculating the TRs, the first ATR is set using the mean TR from the entire period which would not be able to be calculated point in time:

atr[0] = tr[1::].mean()

The effect of this only lasts for the length of the rolling window but shouldn't we set the first ATR value to just the first TR?

I emailed you an example as well.

**Comment by bukosabino** [comment]
Hi @coltonfsmith,

Thank you so much, and sorry about the time delay to answer.

Finally, I have fixed the ATR indicator, and I have written some tests to validate the results (following the dataset on https://school.stockcharts.com/doku.php?id=technical_indicators:average_true_range_atr).

Please, take a look, and let me know your opinion.

Best,
Dario

**Comment by bukosabino** [comment]
The new version (0.5.4) includes this feature.

```sh
pip install --upgrade ta
```
