### ISSUE TITLE
AttributeError: 'TAFeaturesTransform' object has no attribute 'colprefix'

### ISSUE THREAD

**Issue by capster12** [bukosabino/ta#60]
Encountered when running the pipeline example code.

pipe = make_pipeline(
    TAFeaturesTransform("Open", "High", "Low", "Close", "Volume", fillna=True),
    StandardScaler(),
    RandomForestRegressor()
)

y_pred = pipe.fit(X_train, y_train).predict(X_test)

**Comment by bukosabino** [comment]
fixed on last library version (v.0.4.5)

Thanks
