### ISSUE TITLE
LSTM model code for df

### ISSUE THREAD

**Issue by ravinderkonka** [bukosabino/ta#62]
Hi bukosabino,

As you are doing a great work, on ta using python.
Is it possible for you to make , a LSTM(Long short term memory model) using machine learning/data science to predict the stock market prices?.
I heard that, LSTM model is excellent model close to ~90% prediction rate for timeseries data of stocks.

Please let me know, if you need more information.

**Comment by bukosabino** [comment]
Hi @ravinderkonka ,

Yes, LSTM is a famous model used in Machine Learning for Trading. 

But, this topic is outside of the scope of this Technical Analysis Library.
