### ISSUE TITLE
need your whatsapp , or facebook messenger to discuss about lstm and data science related.

### ISSUE THREAD

**Issue by ravinderkonka** [bukosabino/ta#64]
Hi,
Need your whatsapp , or facebook messenger to discuss about lstm and data science related.
Could you please share it?.
Regards,
Ravinder.Konka.
my what'sapp: +91 9603297252

**Comment by bukosabino** [comment]
Hi @ravinderkonka ,

I prefer use my email (bukosabino@gmail.com) or repository issues to discuss about this project.
