### ISSUE TITLE
rsi  with n=30 days value calc 

### ISSUE THREAD

**Issue by ravinderkonka** [bukosabino/ta#65]
Hi,
I would like to calculate rsi for monthly performance, to get long term investment indicators using your  rsi indicator.
Q: I would like to calculate rsi on daily stock market data with n=30 input parameter to your function: rsi(close, n=30, fillna=True),
 will it work?.
Q: will this equiavalent to calculation of rsi(14) on monthly stock market data?
or what i mean is:
will rsi(30) on daily data in dataframe == rsi(14) on monthly data in dataframe?.

**Comment by bukosabino** [comment]
Hi @ravinderkonka ,

You can call rsi indicator using n=30. It will work.

Probably, this affirmation `rsi(30) on daily data in dataframe == rsi(14) on monthly data` is not true, never. But, it make sense to change `n` when you change monthly/daily dataframes.

Best, 
Dario

**Comment by ravinderkonka** [comment]
Hi,

Thank you for your reply.
How do I convert dataframe daily data to dataframe monthly data.?.

Regards,
Ravinder Konka.

On 30 Apr 2019 2:49 p.m., "Darío López Padial" <notifications@github.com>
wrote:

Hi @ravinderkonka <https://github.com/ravinderkonka> ,

You can call rsi indicator using n=30. It will work.

Probably, this affirmation rsi(30) on daily data in dataframe == rsi(14) on
monthly data is not true, never. But, it make sense to change n when you
change monthly/daily dataframes.

Best,
Dario

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bukosabino/ta/issues/65#issuecomment-487876530>, or mute
the thread

**Comment by bukosabino** [comment]
RSI implementation was updated.

Check [this issue](https://github.com/bukosabino/ta/issues/38) to get more info.
