### ISSUE TITLE
rsi(n=30), rsi(n=14) on daily stock data, results in same values

### ISSUE THREAD

**Issue by ravinderkonka** [bukosabino/ta#66]
Hi,
i have a dataframe with daily stock market data for each EoD data i.e for each day one entry in dataframe.
 when i calculate
rsi(n=30), rsi(n=14) on daily stock data, rsi(30) rsi(14) results  same values almost similar values rsi(30) and rsi(14).
please see attached file for example results.
[rsi_30_rsi_14_example_data.txt](https://github.com/bukosabino/ta/files/3123876/rsi_30_rsi_14_example_data.txt)

**Comment by bukosabino** [comment]
Hi @ravinderkonka ,

I don't see the problem with de example results.

**Comment by bukosabino** [comment]
RSI implementation was updated.

Check [this issue](https://github.com/bukosabino/ta/issues/38) to get more info.
