### ISSUE TITLE
 for adx (n=30) getting index 30 is out of bounds for axis 0 with size 11

### ISSUE THREAD

**Issue by ravinderkonka** [bukosabino/ta#67]
Hi,
I am getting exception, when adx(df['close],]n=30,True) is called, please see attached file for dataframe.
[adx_30_index_bound_error.txt](https://github.com/bukosabino/ta/files/3123892/adx_30_index_bound_error.txt)

Traceback (most recent call last):
  File "./algo_trade_signals.py", line 3499, in <module>
    do_identify_multibagger_on_monthly_charts(datetime_object_from_datetime,datetime_object_to_datetime,df)
  File "./algo_trade_signals.py", line 2115, in do_identify_multibagger_on_monthly_charts
    df['adx']=trend.adx(df['high'], df['low'], df['close'], n=30,fillna=True)
  File "/usr/local/lib/python2.7/dist-packages/ta/trend.py", line 179, in adx
    adx[n] = dx[0:n].mean()
IndexError: index 30 is out of bounds for axis 0 with size 11
Q2: why adx values initially for dataframe begining, zeros for more than 30 columns??

**Comment by bukosabino** [comment]
Hi @ravinderkonka,

I don't get any problem using ADX with n=30. 

Please, let me know if you get any more errors.

Best,
Dario
