### ISSUE TITLE
New Indicator proposal: KAMA (Kaufman's Adaptive Moving Average)

### ISSUE THREAD

**Issue by StefanoCore** [bukosabino/ta#68]
Excellent job on developing all these indicators.
Can you please add KAMA - Kaufman's Adaptive Moving Average (https://school.stockcharts.com/doku.php?id=technical_indicators:kaufman_s_adaptive_moving_average) ?

It's an evolution of regular EMA (Esponential Moving Average).

**Comment by bukosabino** [comment]
Hi all,

@d5lewis has worked on a KAMA implementation.

It will be included in the next ta library version (next days).

**Comment by StefanoCore** [comment]
Great!! Thank you! We will test it and let you know!

**Comment by StefanoCore** [comment]
@bukosabino Did you release the new version with KAMA calculation, so we can find it in the "pip3 install ta" library ?

Thanks

**Comment by bukosabino** [comment]
Hi @StefanoCore 

You can install the current development version doing:

`pip install git+https://github.com/bukosabino/ta.git`

I will release asap.

**Comment by bukosabino** [comment]
The indicator was included in the new version updated 0.4.6.
