### ISSUE TITLE
ADX gives nans

### ISSUE THREAD

**Issue by stoiandl** [bukosabino/ta#69]
In adx calculation you have:
`pdm = high.combine(cs, lambda x1, x2: get_min_max(x1, x2, 'max'))`
`pdn = low.combine(cs, lambda x1, x2: get_min_max(x1, x2, 'min'))`

The get_min_max function is not returning the max and min. I believe you forgot to add the returns, i.e. 
`return max(x1, x2)`
`return min(x1, x2)`

**Comment by juliangall** [comment]
Just found this too.

**Comment by bukosabino** [comment]
Hi,

At this moment, ADX implementation works like a charm.

I have implemented some [tests](https://github.com/bukosabino/ta/blob/f0acf1a82027fd9bb6d822a1afc10e051ed36241/ta/tests/trend.py#L9) in the library based on the dataset provided by [Stockcharts](http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx).

Best,
Dario
