### ISSUE TITLE
Incorrect Bollinger low and high calculation

### ISSUE THREAD

**Issue by juliangall** [bukosabino/ta#74]
Bollinger low and high calculate the standard deviation as follows:

```python
mstd = close.rolling(n, min_periods=0).std()
```

According to the Pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.Rolling.std.html), std() uses (N - ddof) as the denominator, where ddof defaults to 1, unlike numpy std().

[StockCharts](https://school.stockcharts.com/doku.php?id=technical_indicators:bollinger_bands) has an example of Bollinger in Excel which, unsurprisingly, uses N as the denominator. [Wikipedia](https://en.wikipedia.org/wiki/Standard_deviation) explains that N - 1 is used if the sd is being calculated from a sample of the population, rather than the whole. As this is rolling, and a very small set of numbers, I assume Pandas is calculating the actual sd from all the data fed to it, therefore we should use N.

The high and low band Bollinger calcs should be:

```python
mstd = close.rolling(n, min_periods=0).std(ddof=0)
```

The same applies to the Bollinger indicators.

**Comment by bukosabino** [comment]
Hi @juliangall ,

You are right.

I have included your proposal code in the last version (0.4.7). You can use it updating the library installation:

```sh
pip install --upgrade ta
```

Thank you.
