### ISSUE TITLE
trend_adx always calculates to 20

### ISSUE THREAD

**Issue by amanbedi23** [bukosabino/ta#80]
not sure why the trend_adx indicator always calculates to 20.

**Comment by bukosabino** [comment]
Hi @amanbedi23 ,

At this moment ADX implementation works like a charm.

In fact, I have implemented some [tests](https://github.com/bukosabino/ta/blob/f0acf1a82027fd9bb6d822a1afc10e051ed36241/ta/tests/trend.py#L9) in the library based on the dataset provided by [Stockcharts](http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_directional_index_adx).

Probably, you try with a really small dataset. ADX indicator needs a dataset with more than 14 rows to get any results. 

Best,
Dario
