### ISSUE TITLE
force_index calculation incorrect

### ISSUE THREAD

**Issue by rsandx** [bukosabino/ta#81]
I found the Force Index formula fi = close.diff(n) * volume.diff(n) gives results very different to those of the charting software TC2000.

According to stockcharts.com, the formula should be:
Force Index(1) = {Close (current period)  -  Close (prior period)} x Volume
Force Index(n) = n-period EMA of Force Index(1)

So the formula should be implemented as:
    fi1 = close.diff(1) * volume
    fi = fi1.ewm(span=n).mean()

Please review it.

**Comment by bukosabino** [comment]
Hi @rsandx ,

I have fixed the Force Index indicator, and I have written some tests to validate the results (following the dataset provided by [stockcharts](https://school.stockcharts.com/doku.php?id=technical_indicators:force_index)).

Please, take a look at this [commit](https://github.com/bukosabino/ta/pull/89/commits/43a014d4b0e3f99df3ba78222a89870f199d5b52), and let me know your opinion.

Best,
Dario

**Comment by bukosabino** [comment]
The new implementation was included in the last version (0.5.6). Instructions to update:

```sh
pip install --upgrade ta
```

or 

```sh
pip install ta==0.5.6
```

Best,
Dario
