### ISSUE TITLE
Naming of Indicators

### ISSUE THREAD

**Issue by Fransenson** [bukosabino/ta#9]
Hey there! I just fiddled around with your library and I really like it. One thing that feels kinda strange: when applying all indicators, the header just states "trend1" and so on, not the name of the actual indicator. This makes working with it quite tough.

Any chance that I missed something here?

Thank you!

**Comment by bukosabino** [comment]
Hi @Fransenson ,

Good idea. I have reimplemented a new version (0.1.7) with your advice.

If you want to use others names for the features/columns you can change them on wrapper.py: https://github.com/bukosabino/ta/blob/master/ta/wrapper.py

**Comment by Fransenson** [comment]
Thank you for the quick response! That's awesome. I updated and am now happy with the headers. 

Cheers!
