### ISSUE TITLE
macd from ta/trend.py seems to have duplicate def and some errors?

### ISSUE THREAD

**Issue by dreamerx88** [bukosabino/ta#95]
I'm new to coding but noticed macd_signal definition in class macd shown on lines 123 & 124 in ta/trend.py https://github.com/bukosabino/ta/blob/master/ta/trend.py specifies "macd_diff" instead of "macd_signal"

And why is there another set of definitions for macd, macd_signal, and macd_hist on lines 661, 681 and 701? Which definitions get called from ta macd or macd_signal is invoked?

**Comment by bukosabino** [comment]
Hi @dreamerx88,

You are right; the name of the variable is confusing. I will update the code. Also, I will write some tests to check the 3 MACD outputs are right.

Recently I have migrated from functions definition (lines 661, 681, and 701) to class-based style code. So, at this moment, there are two possible ways to call the functions. But, I recommend using the new class-based API: https://technical-analysis-library-in-python.readthedocs.io/en/latest/ta.html#ta.trend.MACD

Best,
Dario

**Comment by bukosabino** [comment]
Hi, 

I have fixed some errors on MACD Indicator, and I have included the changes in the new ta library version (v0.5.7). Please, update your local environment:

```python
pip install --upgrade ta
```
